// <auto-generated />
namespace CinemaApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class MovieConstraints : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MovieConstraints));
        
        string IMigrationMetadata.Id
        {
            get { return "201907171011515_MovieConstraints"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
